    public enum Area
    {
        NONE = 1,
        TRAINING_GARDEN = 2,
        ENCHANTED_FOREST = 4,
        SANDY_ISLAND = 8,
        ICE_PALACE = 16,
        CASTLE = 32,
        ARENA = 64
    }

    public enum TokenType { NONE, BLOCKER, STICKY, WATER, GHOST, ARROW, FOURWAY_ARROW, BOUNCE, ICE, ICE_BLOCK, SAND, TRAPDOOR, PIT, CIRCLE_BOMB, CROSS_BOMB, QUICKSAND, WIND, PORTAL, SNOW, FRUIT, LURE, GOLD, RIGHT_TURN, LEFT_TURN, GUARD, TOGGLE_ROTATE, TOGGLE_FLIP, ROTATING_ARROW, POPUP_BLOCKER, SNOWMAN, COLD, FIRE, CURRENT, HEX, GRASS, SHARK, WEB, SPIDER, FLOWERS, WALL, ZONE, SWITCH, RANDOM_FOURWAY, RANDOM_UPDOWN, RANDOM_LEFTRIGHT, PUDDLE, GLASS_BLOCK, FOUNTAIN,
        WISP, MOVING_GHOST,MOVING_CLOUD, MOVING_SUN, MUD, VOLCANO, LAVA, FRUIT_TREE,
        ARROW_ONCE, FALLAWAY_FLOOR, THIN_ICE, ARROW_ACTIVATE, SPRINGY_BLOCKER, MOVE_BLOCKER,
        HIDDEN_BOMB
    }